### Libraries

In [32]:
import numpy as np
from numpy.linalg import inv
from numpy import linalg as LA
from numpy import matmul
from scipy.linalg import lu
from sympy import symbols, Eq, solve
from statistics import variance
import statistics as stat
from scipy import stats
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor

## Workspace

### Nearest neighbour

In [6]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y)
print(neigh.predict([[1.1],[2.4]]))
print(neigh.predict_proba([[1.1],[2.4]]))

[0 1]
[[0.66666667 0.33333333]
 [0.33333333 0.66666667]]


In [7]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
neigh = KNeighborsRegressor(n_neighbors=2)
neigh.fit(X, y)
print(neigh.predict([[1.5]]))

[0.5]


### Decision tree

In [29]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X,y)
print(clf.predict([[1.1],[2.4]]))

[0 1]


In [24]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
reg = DecisionTreeRegressor(random_state=0)
reg.fit(X, y)
print(reg.predict([[1.5],[2],[4]]))

[0. 1. 1.]


In [31]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
clf = RandomForestClassifier(random_state=0)
clf.fit(X,y)
print(clf.predict([[1.1],[2.4]]))

[0 1]


In [33]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
reg = RandomForestRegressor(max_depth=2, random_state=0)
reg.fit(X, y)
print(reg.predict([[1.5],[2],[4]]))

[0.24 0.69 0.91]


### Neural network

In [19]:
from sklearn.neural_network import MLPClassifier
X = [[0., 0.], [1., 1.]]
y = [0, 1]
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 3), random_state=1)
clf.fit(X, y)
y_p = clf.predict([[2., 2.], [-1., -2.]])
print("pridicted value = ",y_p)
print("shape of the coefficients = ",[coef.shape for coef in clf.coefs_])
print("coefficients = ",clf.coefs_)
print("intercepts = ",clf.intercepts_)

pridicted value =  [1 0]
shape of the coefficients =  [(2, 5), (5, 3), (3, 4), (4, 1)]
coefficients =  [array([[-0.1534858 ,  7.90088182, -0.92464689, -2.47609656, -0.6534016 ],
       [-0.75405819,  6.91301409, -0.28566893, -2.30141873,  0.07179997]]), array([[ 0.2949517 , -0.14308351,  0.10154818],
       [-0.52833572, -0.9386695 ,  1.37039847],
       [ 0.8102104 , -0.32282314,  0.33276654],
       [ 1.26012107, -0.27246214, -7.5372787 ],
       [-0.79755126, -0.57127649,  0.65428172]]), array([[ 0.06134639,  0.35491834, -0.34124386,  1.08806488],
       [ 0.81207255, -0.53220216,  0.46269617,  0.90425462],
       [-1.89101115, -3.45908306,  6.76578265, -0.73391956]]), array([[ 0.07211119],
       [ 0.30885511],
       [ 9.08677449],
       [-0.8370695 ]])]
intercepts =  [array([-0.14962269,  0.87673271, -0.5472481 ,  7.60364182, -0.87510813]), array([-0.57959025, -1.24030913,  0.92695735]), array([-2.64081412, -2.00587731, -0.40305132, -0.06105139]), array([-4.221964])]


In [21]:
from sklearn.neural_network import MLPClassifier
X = [[0., 0.], [1., 1.]]
y = [0, 1]
reg = MLPRegressor(random_state=1,hidden_layer_sizes=(6,3,2), max_iter=500).fit(X, y)
reg.fit(X, y)
y_p = reg.predict([[2., 2.], [-1., -2.]])
print("pridicted value = ",y_p)
print("shape of the coefficients = ",[coef.shape for coef in reg.coefs_])
print("coefficients = ",reg.coefs_)
print("intercepts = ",reg.intercepts_)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


pridicted value =  [-0.65049651 -0.85858568]
shape of the coefficients =  [(2, 6), (6, 3), (3, 2), (2, 1)]
coefficients =  [array([[-1.32617776e-05,  2.39180671e-01, -4.36936063e-01,
        -2.15208243e-01, -2.16065345e-01, -2.95081485e-01],
       [-1.62168211e-01, -4.09907579e-01, -3.60948801e-04,
         1.94381396e-01, -7.68733226e-06,  2.69477667e-02]]), array([[-1.96293664e-01, -1.25082082e-01,  1.23748710e-01],
       [ 6.28565378e-01,  1.84639827e-02,  2.44091967e-02],
       [ 2.18345367e-01,  2.42826559e-01, -2.70744295e-01],
       [-9.60626779e-01, -1.44506738e-01,  2.20678509e-01],
       [-2.52429857e-01, -9.58917999e-07,  3.31275083e-01],
       [-1.70501809e-01,  5.57581622e-01, -1.99432566e-02]]), array([[ 0.45116321,  0.97293044],
       [ 0.27813507, -0.80710952],
       [ 0.23403545, -0.44008679]]), array([[-0.50144188],
       [-0.46141584]])]
intercepts =  [array([-0.51190372,  0.50205743, -0.8185887 ,  0.44521649, -0.14323228,
        0.25160434]), array([ 0.14

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


## End

In [ ]:
a = [80,40]
mean = np.mean(a)
std = np.std(a)
var = np.var(a)
var_samp = stat.variance(a)
mean_samp = stat.mean(a)
std_samp = stat.stdev(a)
print("mean = ",mean)
print("std = ", std)
print("var = ", var)
print("mean_samp = ", mean_samp)
print("var_samp = ", var_samp)
print("std_samp = ", std_samp)

mean =  60.0
std =  20.0
var =  400.0
mean_samp =  60
var_samp =  800
std_samp =  28.284271247461902


In [ ]:
x = [-3.37,-2.6,6.05,1.76,-6.11,-3.07,-6.46,0.39,5.31,4.13]
y = [-3.3,-2.53,6.12,1.83,-6.04,-3,-6.39,0.46,5.38,4.2]
corr_spearman = stats.spearmanr(x,y)
corr_pearson = stats.pearsonr(x, y)
corr_kendall = stats.kendalltau(x, y)
print("corr_spearman = ",corr_spearman)
print("corr_pearson = ",corr_pearson)
print("corr_kendall = ",corr_kendall)

corr_spearman =  SpearmanrResult(correlation=0.9999999999999999, pvalue=6.646897422032013e-64)
corr_pearson =  (0.9999999999999998, 1.0635035875250972e-62)
corr_kendall =  KendalltauResult(correlation=0.9999999999999999, pvalue=5.511463844797178e-07)


In [ ]:
x = np.array([[13.38,6.82],[9.7,12.66],[11.61,11.41],[7.9,8.73],[6.03,5.86],[14.53,11.81],[9.49,6.18],[5.03,9.11],[12.59,10.9],[5.25,7.2]])
y = np.array([43.18,64.82,67.83,50.66,26.57,58.57,39.23,33.14,61.03,36.37])
reg = LinearRegression().fit(x, y)
print("coefficients = ",reg.coef_)
print("intercept = ",reg.intercept_)
y_p = reg.predict(x)
r2_score = metrics.r2_score(y, y_p)
print("r2_score = ",r2_score)

coefficients =  [1.48741945 4.09370089]
intercept =  -3.1880227844911886
r2_score =  0.8622386152677342


In [ ]:
"""import statsmodels.api as sm
sm.qqplot(y_p-y, line ='45')"""

"import statsmodels.api as sm\nsm.qqplot(y_p-y, line ='45')"

In [ ]:
error = y_p - y
print(error)
mean_samp = np.mean(error)
std_samp = stat.stdev(error)
#std_samp = np.std(error)
print("mean_samp = ", mean_samp)
print("std_samp = ", std_samp)
var = np.mean(error*error)
print(np.sqrt(var))

[ 1.45268946 -1.75380091 -7.03995588 -6.35940041  3.20020368  8.20078926
 -3.00334075  8.44731212 -0.87007228 -2.2744243 ]
mean_samp =  -2.842170943040401e-15
std_samp =  5.364393867297803
5.08911086607003


In [ ]:
x = np.array([7.93,4.83,5.8,4.37,4.93,6.21,8.46,5.14,0.22,6.36])
y = np.array([11.94,10.74,10.12,9.52,11.73,10.32,12.91,11.63,6.64,11.89])
y_p = 0.7*x+6.97
r2_score = metrics.r2_score(y, y_p)
print("r2_score = ",r2_score)

r2_score =  0.7913007105382268


In [ ]:
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
x1 = np.array([[11.9,16.9,17.2,16.9,12.5,7.7,6,1.1,5.5,9.6]])
x2 = np.array([[4.2,2.7,2.3,4.3,2.0,3.4,2.2,4.8,1.1,4.4]])
x3 = np.array([[2.6,4.1,2.8,3.6,3.7,3.1,2.9,3.9,1,2.6]])
x4 = np.array([[1.3,3.8,1.5,1.1,2,1.2,1.5,2.2,4.6,2.5]])
x5 = np.array([[9,2,2,8,4,7,8,3,1,4]])
x = np.append(x1,x2,axis=0)
x = np.append(x,x5,axis=0)
x = np.append(x,x3,axis=0)
#x = x1
x = x.T
y = np.array([61.59,64.99,64.46,49.02,34.25,79.37,80.54,76.22,34.25,78.59])
x = sm.add_constant(x)
print(x)
model = sm.OLS(y, x).fit()
print(model.aic)

[[ 1.  11.9  4.2  9.   2.6]
 [ 1.  16.9  2.7  2.   4.1]
 [ 1.  17.2  2.3  2.   2.8]
 [ 1.  16.9  4.3  8.   3.6]
 [ 1.  12.5  2.   4.   3.7]
 [ 1.   7.7  3.4  7.   3.1]
 [ 1.   6.   2.2  8.   2.9]
 [ 1.   1.1  4.8  3.   3.9]
 [ 1.   5.5  1.1  1.   1. ]
 [ 1.   9.6  4.4  4.   2.6]]
90.75308430035648


In [ ]:
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
x = np.array([[7.2,8.1,10.8,26.1,24.9,2.4]])
x = np.append(x,(x*x),axis=0)
x = x.T
y = np.array([202.8,268.2,575.7,6579.6,5701.5,26.1])
x = sm.add_constant(x)
print(x)
model = sm.OLS(y, x).fit()
print(model.bic)

[[  1.     7.2   51.84]
 [  1.     8.1   65.61]
 [  1.    10.8  116.64]
 [  1.    26.1  681.21]
 [  1.    24.9  620.01]
 [  1.     2.4    5.76]]
72.54497507577024


In [ ]:
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
x1 = np.array([[7.2,8.1,10.8,26.1,24.9,2.4]])
x = np.append(x1,(x1*x1),axis=0)
x = np.append(x,(x1*x1*x1),axis=0)
x = np.append(x,(x1*x1*x1*x1),axis=0)
x = np.append(x,(x1*x1*x1*x1*x1),axis=0)
x = np.append(x,(x1*x1*x1*x1*x1*x1),axis=0)
x = x.T
y = np.array([202.8,268.2,575.7,6579.6,5701.5,26.1])
x = sm.add_constant(x)
#print(x)
model = sm.OLS(y, x).fit()
print(model.bic)

-178.08436094437795
